-- UFRMP dashboard tables for Supabase.
-- Run once in the Supabase dashboard: SQL Editor > New query > paste > Run.
-- Safe to re-run. The dashboard seeds empty tables itself on first load.
--
-- Access: the page uses the public "anon" key, so these policies let anyone
-- with the dashboard link read and edit the data (the same model as the
-- earlier SheetDB/Google Sheet setup). Tighten them if that changes.

-- One row per work item; the full work object is kept in `data`.
create table if not exists public.works (
  id          text primary key,
  data        jsonb not null default '{}'::jsonb,
  seq         bigint generated by default as identity,  -- keeps the original display order
  updated_at  timestamptz not null default now()
);

-- One row per Implementation Gantt line, grouped by city programme.
create table if not exists public.gantt_data (
  id          text primary key,
  city_id     text not null,
  data        jsonb not null default '{}'::jsonb,  -- name, budgetCr, endDate, pctComplete, remarks, fills
  seq         bigint generated by default as identity,
  updated_at  timestamptz not null default now()
);
create index if not exists gantt_data_city_id_idx on public.gantt_data (city_id);

-- One row per Budget Matrix line item, grouped by city programme.
create table if not exists public.budget_matrix (
  id          text primary key,
  city_id     text not null,
  data        jsonb not null default '{}'::jsonb,  -- name, description, geo, agency, estCr, ndmfCr, stateCr, category, type, timeline, remarks
  seq         bigint generated by default as identity,
  updated_at  timestamptz not null default now()
);
create index if not exists budget_matrix_city_id_idx on public.budget_matrix (city_id);

-- Everything else (components, dprs, timelines, cityProgrammes, meData,
-- photos:<workId>, migration flags) as one JSON string per key.
create table if not exists public.kv_store (
  key         text primary key,
  value       text not null,
  updated_at  timestamptz not null default now()
);

do $$
declare t text;
begin
  foreach t in array array['works','gantt_data','budget_matrix','kv_store'] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists "dashboard read" on public.%I', t);
    execute format('drop policy if exists "dashboard insert" on public.%I', t);
    execute format('drop policy if exists "dashboard update" on public.%I', t);
    execute format('drop policy if exists "dashboard delete" on public.%I', t);
    execute format('create policy "dashboard read" on public.%I for select to anon, authenticated using (true)', t);
    execute format('create policy "dashboard insert" on public.%I for insert to anon, authenticated with check (true)', t);
    execute format('create policy "dashboard update" on public.%I for update to anon, authenticated using (true) with check (true)', t);
    execute format('create policy "dashboard delete" on public.%I for delete to anon, authenticated using (true)', t);
    execute format('grant select, insert, update, delete on public.%I to anon, authenticated', t);
  end loop;
end $$;
