-- UFRMP dashboard tables, logins and access rules for Supabase.
-- Run in the Supabase dashboard: SQL Editor > New query > paste > Run.
-- Safe to re-run. The dashboard seeds empty tables itself on the master's first load.
--
-- Access: nobody can read or change data without signing in. Each login has a
-- row in user_profiles saying whether it is the master login (sees and edits
-- every city) or a city login (sees and edits only its own city). These rules
-- are enforced by Postgres row-level security, so they hold even for someone
-- calling Supabase directly with the public anon key from the page.
-- Logins are created and edited by the master on the "User Logins" page, which
-- calls the ufrmp-admin Edge Function (supabase/functions/ufrmp-admin).
-- See supabase/SETUP.md for the one-time setup steps.

-- One row per work item; the full work object is kept in `data`.
create table if not exists public.works (
  id          text primary key,
  data        jsonb not null default '{}'::jsonb,
  seq         bigint generated by default as identity,  -- keeps the original display order
  updated_at  timestamptz not null default now()
);
alter table public.works add column if not exists city_id text;  -- city programme the work belongs to
create index if not exists works_city_id_idx on public.works (city_id);

-- One row per Implementation Gantt line, grouped by city programme.
create table if not exists public.gantt_data (
  id          text primary key,
  city_id     text not null,
  data        jsonb not null default '{}'::jsonb,  -- name, budgetCr, endDate, pctComplete, remarks, fills
  seq         bigint generated by default as identity,
  updated_at  timestamptz not null default now()
);
create index if not exists gantt_data_city_id_idx on public.gantt_data (city_id);

-- One row per Budget Matrix line item, grouped by city programme.
create table if not exists public.budget_matrix (
  id          text primary key,
  city_id     text not null,
  data        jsonb not null default '{}'::jsonb,  -- name, description, geo, agency, estCr, ndmfCr, stateCr, category, type, timeline, remarks
  seq         bigint generated by default as identity,
  updated_at  timestamptz not null default now()
);
create index if not exists budget_matrix_city_id_idx on public.budget_matrix (city_id);

-- Everything else as one JSON string per key. City data is kept one key per
-- city ("components@<cityId>", "dprs@<cityId>", "timelines@<cityId>",
-- "meData@<cityId>", "cityProgrammes@<cityId>", "photos:<workId>") with that
-- city in city_id. Keys with no city_id (migration flags) are master-only.
create table if not exists public.kv_store (
  key         text primary key,
  value       text not null,
  updated_at  timestamptz not null default now()
);
alter table public.kv_store add column if not exists city_id text;
create index if not exists kv_store_city_id_idx on public.kv_store (city_id);

-- ------------------------------------------------------------------
-- Logins: one profile per Supabase Auth user.
-- Usernames sign in as "<username>@ufrmp.local" behind the scenes; the
-- dashboard and the Edge Function both build that address.
-- ------------------------------------------------------------------
create table if not exists public.user_profiles (
  user_id     uuid primary key references auth.users (id) on delete cascade,
  username    text not null,
  role        text not null check (role in ('master', 'city')),
  city_id     text,
  created_at  timestamptz not null default now(),
  constraint user_profiles_role_city check ((role = 'master' and city_id is null) or (role = 'city' and city_id is not null))
);
create unique index if not exists user_profiles_username_key on public.user_profiles (lower(username));

create or replace function public.ufrmp_is_master() returns boolean
language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.user_profiles where user_id = auth.uid() and role = 'master');
$$;

create or replace function public.ufrmp_user_city() returns text
language sql stable security definer set search_path = public as $$
  select city_id from public.user_profiles where user_id = auth.uid() and role = 'city';
$$;

revoke all on function public.ufrmp_is_master() from public, anon;
revoke all on function public.ufrmp_user_city() from public, anon;
grant execute on function public.ufrmp_is_master() to authenticated;
grant execute on function public.ufrmp_user_city() to authenticated;

alter table public.user_profiles enable row level security;
drop policy if exists "read own or all as master" on public.user_profiles;
create policy "read own or all as master" on public.user_profiles for select to authenticated
  using (user_id = auth.uid() or (select public.ufrmp_is_master()));
-- No insert/update/delete policies: profiles change only through the Edge Function.
revoke all on public.user_profiles from anon, authenticated;
grant select on public.user_profiles to authenticated;

-- Readable copies of passwords set from the User Logins page, so the master
-- can look them up (Sriram's choice, 2026-10-08). Only the master can read
-- them; only the ufrmp-admin Edge Function writes them. Passwords set before
-- this table existed have no copy.
create table if not exists public.login_passwords (
  user_id     uuid primary key references auth.users (id) on delete cascade,
  password    text not null,
  updated_at  timestamptz not null default now()
);
alter table public.login_passwords enable row level security;
drop policy if exists "master reads" on public.login_passwords;
create policy "master reads" on public.login_passwords for select to authenticated
  using ((select public.ufrmp_is_master()));
revoke all on public.login_passwords from anon, authenticated;
grant select on public.login_passwords to authenticated;

-- ------------------------------------------------------------------
-- Row-level security on the data tables: the master can do anything, a city
-- login only touches rows whose city_id is its own city. The anon key alone
-- gets nothing.
-- ------------------------------------------------------------------
do $$
declare t text;
begin
  foreach t in array array['works','gantt_data','budget_matrix','kv_store'] loop
    execute format('alter table public.%I enable row level security', t);
    -- policies from the earlier open setup
    execute format('drop policy if exists "dashboard read" on public.%I', t);
    execute format('drop policy if exists "dashboard insert" on public.%I', t);
    execute format('drop policy if exists "dashboard update" on public.%I', t);
    execute format('drop policy if exists "dashboard delete" on public.%I', t);
    execute format('drop policy if exists "master or own city" on public.%I', t);
    execute format('create policy "master or own city" on public.%I for all to authenticated '
                   'using ((select public.ufrmp_is_master()) or city_id = (select public.ufrmp_user_city())) '
                   'with check ((select public.ufrmp_is_master()) or city_id = (select public.ufrmp_user_city()))', t);
    execute format('revoke all on public.%I from anon', t);
    execute format('grant select, insert, update, delete on public.%I to authenticated', t);
  end loop;
end $$;

-- A per-city key must name the same city as its city_id, so a city login
-- can't plant "components@<another city>".
drop policy if exists "per-city keys match city" on public.kv_store;
create policy "per-city keys match city" on public.kv_store as restrictive for all to authenticated
  using (true)
  with check (position('@' in key) = 0 or key = split_part(key, '@', 1) || '@' || city_id);

-- ------------------------------------------------------------------
-- One-time move of the earlier shared data into the per-city layout.
-- Does nothing once the old keys are gone. Items whose city can't be worked
-- out stay under the old key, which only the master can see.
-- ------------------------------------------------------------------
create or replace function public.ufrmp_merge_by_id(a jsonb, b jsonb) returns jsonb
language sql immutable as $$
  select coalesce(a, '[]'::jsonb) || coalesce(
    (select jsonb_agg(e order by ord) from jsonb_array_elements(coalesce(b, '[]'::jsonb)) with ordinality as x(e, ord)
      where not exists (select 1 from jsonb_array_elements(coalesce(a, '[]'::jsonb)) o where o->>'id' = e->>'id')),
    '[]'::jsonb);
$$;

create or replace function public.ufrmp_split_legacy_array(coll text, city_of jsonb) returns void
language plpgsql as $$
-- city_of maps item id -> city id for this collection's items
declare legacy jsonb; leftover jsonb;
begin
  select value::jsonb into legacy from public.kv_store where key = coll;
  if legacy is null or jsonb_typeof(legacy) <> 'array' then return; end if;

  insert into public.kv_store (key, value, city_id, updated_at)
    select coll || '@' || g.city, g.items::text, g.city, now()
    from (
      select city_of->>(e->>'id') as city, jsonb_agg(e order by ord) as items
      from jsonb_array_elements(legacy) with ordinality as x(e, ord)
      where coalesce(city_of->>(e->>'id'), '') <> ''
      group by 1
    ) g
  on conflict (key) do update
    set value = public.ufrmp_merge_by_id(public.kv_store.value::jsonb, excluded.value::jsonb)::text,
        city_id = excluded.city_id, updated_at = now();

  select jsonb_agg(e order by ord) into leftover
    from jsonb_array_elements(legacy) with ordinality as x(e, ord)
    where coalesce(city_of->>(e->>'id'), '') = '';
  if leftover is null then
    delete from public.kv_store where key = coll;
  else
    update public.kv_store set value = leftover::text, city_id = null, updated_at = now() where key = coll;
  end if;
end $$;

revoke all on function public.ufrmp_merge_by_id(jsonb, jsonb) from public, anon, authenticated;
revoke all on function public.ufrmp_split_legacy_array(text, jsonb) from public, anon, authenticated;

do $$
declare
  comp_city jsonb;
begin
  -- City programmes: one key per city.
  perform public.ufrmp_split_legacy_array('cityProgrammes',
    (select coalesce(jsonb_object_agg(e->>'id', e->>'id'), '{}'::jsonb)
       from public.kv_store k, jsonb_array_elements(k.value::jsonb) e
      where k.key = 'cityProgrammes' and coalesce(e->>'id', '') <> ''));

  -- Components carry their city in cityProgrammeId.
  perform public.ufrmp_split_legacy_array('components',
    (select coalesce(jsonb_object_agg(e->>'id', e->>'cityProgrammeId'), '{}'::jsonb)
       from public.kv_store k, jsonb_array_elements(k.value::jsonb) e
      where k.key = 'components' and coalesce(e->>'id', '') <> '' and coalesce(e->>'cityProgrammeId', '') <> ''));

  -- Component id -> city, from the per-city keys now in place.
  select coalesce(jsonb_object_agg(e->>'id', k.city_id), '{}'::jsonb) into comp_city
    from public.kv_store k, jsonb_array_elements(k.value::jsonb) e
   where k.key like 'components@%' and coalesce(e->>'id', '') <> '';

  -- DPRs and approval timelines belong to a component.
  perform public.ufrmp_split_legacy_array('dprs',
    (select coalesce(jsonb_object_agg(e->>'id', comp_city->>(e->>'componentId')) filter (where comp_city ? (e->>'componentId')), '{}'::jsonb)
       from public.kv_store k, jsonb_array_elements(k.value::jsonb) e
      where k.key = 'dprs' and coalesce(e->>'id', '') <> ''));
  perform public.ufrmp_split_legacy_array('timelines',
    (select coalesce(jsonb_object_agg(e->>'id', comp_city->>(e->>'componentId')) filter (where comp_city ? (e->>'componentId')), '{}'::jsonb)
       from public.kv_store k, jsonb_array_elements(k.value::jsonb) e
      where k.key = 'timelines' and coalesce(e->>'id', '') <> ''));

  -- M&E data is an object keyed by city id.
  insert into public.kv_store (key, value, city_id, updated_at)
    select 'meData@' || m.key, jsonb_build_object(m.key, m.value)::text, m.key, now()
      from public.kv_store k, jsonb_each(k.value::jsonb) m
     where k.key = 'meData' and jsonb_typeof(k.value::jsonb) = 'object'
  on conflict (key) do nothing;
  delete from public.kv_store where key = 'meData';

  -- Works: city via DPR -> component.
  update public.works w set city_id = d.city
    from (
      select e->>'id' as dpr_id, comp_city->>(e->>'componentId') as city
        from public.kv_store k, jsonb_array_elements(k.value::jsonb) e
       where k.key like 'dprs@%'
    ) d
   where w.city_id is null and d.dpr_id = w.data->>'dprId' and d.city is not null;

  -- Photos follow their work.
  update public.kv_store p set city_id = w.city_id
    from public.works w
   where p.city_id is null and p.key = 'photos:' || w.id and w.city_id is not null;
end $$;
